import type { LocationContext, PropertyContext, ScannedSource, ScannerInsight, ScannerReport, ScannerRun } from "@/lib/types";

export const mockScannerRuns: ScannerRun[] = [
  {
    id: "scan_biarritz_airbnb_pains",
    userId: "user_001",
    campaignId: "camp_biarritz_premium",
    prospectId: "pros_biarritz_ocean",
    name: "Biarritz — Airbnb problèmes hôtes",
    objective: "find_sales_angles",
    city: "Biarritz",
    country: "France",
    neighborhood: "Centre, Côte des Basques, Anglet",
    targetType: "Hôtes premium et conciergeries",
    sources: ["search_engine", "reddit", "forum", "local_press", "concierge_site", "tourism_office"],
    keywords: "Airbnb Biarritz parking check-in surf voyageurs internationaux conciergerie",
    language: "fr",
    depth: "standard",
    volume: 30,
    status: "completed",
    progress: 100,
    logs: [
      "Run créé avec politique public-only et connecteurs mockés.",
      "Recherche moteur interne: 18 résultats normalisés.",
      "Connecteur Reddit mock: 4 discussions pertinentes.",
      "Analyse IA interne: 9 pain points détectés.",
      "Enrichissement prospect Ocean Key préparé.",
    ],
    startedAt: "2026-05-05T09:12:00.000Z",
    completedAt: "2026-05-05T09:17:00.000Z",
    createdAt: "2026-05-05T09:10:00.000Z",
    updatedAt: "2026-05-05T09:17:00.000Z",
  },
  {
    id: "scan_chamonix_chalet",
    userId: "user_001",
    campaignId: "camp_biarritz_premium",
    prospectId: "pros_chamonix_multilingual",
    name: "Chamonix — Chalet Airbnb et besoins montagne",
    objective: "understand_property_type",
    city: "Chamonix",
    country: "France",
    neighborhood: "Centre, Argentière, Les Praz",
    targetType: "Chalets, multi-propriétaires, conciergeries montagne",
    sources: ["search_engine", "forum", "tourism_office", "owner_site", "public_listing"],
    keywords: "Chamonix chalet Airbnb neige chauffage ski arrivée nuit voyageurs anglais",
    language: "fr",
    depth: "deep",
    volume: 25,
    status: "completed",
    progress: 100,
    logs: ["Sources montagne normalisées.", "Signaux météo et accès neige détectés.", "FAQ probable générée pour Concierge IA."],
    startedAt: "2026-05-04T15:05:00.000Z",
    completedAt: "2026-05-04T15:12:00.000Z",
    createdAt: "2026-05-04T15:02:00.000Z",
    updatedAt: "2026-05-04T15:12:00.000Z",
  },
  {
    id: "scan_paris_studio",
    userId: "user_001",
    campaignId: "camp_paris_hosts",
    prospectId: "pros_paris_camille",
    name: "Paris — Studio urbain, check-in et métro",
    objective: "find_guest_problems",
    city: "Paris",
    country: "France",
    neighborhood: "Marais, Montmartre, Saint-Germain",
    targetType: "Studios et appartements urbains",
    sources: ["search_engine", "reddit", "forum", "local_press", "public_listing"],
    keywords: "Paris Airbnb studio check-in métro bruit ascenseur règlement copropriété",
    language: "fr",
    depth: "standard",
    volume: 25,
    status: "ai_analysis",
    progress: 68,
    logs: ["Collecte publique terminée.", "Analyse bruit, ascenseur, métro en cours.", "Scoring enrichi en préparation."],
    startedAt: "2026-05-05T16:02:00.000Z",
    completedAt: null,
    createdAt: "2026-05-05T16:00:00.000Z",
    updatedAt: "2026-05-05T16:05:00.000Z",
  },
];

export const mockScannedSources: ScannedSource[] = [
  {
    id: "src_biarritz_forum_parking",
    scannerRunId: "scan_biarritz_airbnb_pains",
    sourceType: "forum",
    sourceName: "Forum voyage public",
    title: "Biarritz en été: stationnement très compliqué près des plages",
    url: "https://example.com/forum/biarritz-parking-ete",
    snippet: "Plusieurs voyageurs recommandent d'anticiper le parking et les arrivées tardives près de la Côte des Basques.",
    extractedText: "Parking difficile en haute saison, accès plage saturé, nécessité d'instructions claires avant arrivée.",
    authorName: "Voyageur public",
    publishedAt: "2026-04-14T08:00:00.000Z",
    relevanceScore: 91,
    credibilityScore: 72,
    legalStatus: "allowed_public",
    createdAt: "2026-05-05T09:13:00.000Z",
  },
  {
    id: "src_biarritz_reddit_questions",
    scannerRunId: "scan_biarritz_airbnb_pains",
    sourceType: "reddit",
    sourceName: "Reddit API mock",
    title: "Guests keep asking the same arrival and beach questions",
    url: "https://reddit.example/r/airbnbhosts/comments/mock",
    snippet: "Host complains that guests repeatedly ask about check-in, parking, beach access, restaurants and late checkout.",
    extractedText: "Repeated guest messages: check-in, Wi-Fi, parking, restaurants, beach gear, late checkout. Host wants automation.",
    authorName: "u/mock_host",
    publishedAt: "2026-03-21T12:10:00.000Z",
    relevanceScore: 94,
    credibilityScore: 68,
    legalStatus: "official_api_preferred",
    createdAt: "2026-05-05T09:13:30.000Z",
  },
  {
    id: "src_biarritz_local_press_season",
    scannerRunId: "scan_biarritz_airbnb_pains",
    sourceType: "local_press",
    sourceName: "Presse locale publique",
    title: "La saison estivale renforce la pression touristique à Biarritz",
    url: "https://example.com/presse/biarritz-saison-ete",
    snippet: "La fréquentation estivale augmente les besoins d'accueil, mobilité et recommandations locales.",
    extractedText: "Saisonnalité forte, voyageurs internationaux, mobilité compliquée, activités surf, restauration demandée.",
    publishedAt: "2026-04-02T07:20:00.000Z",
    relevanceScore: 88,
    credibilityScore: 81,
    legalStatus: "allowed_public",
    createdAt: "2026-05-05T09:14:00.000Z",
  },
  {
    id: "src_chamonix_forum_snow",
    scannerRunId: "scan_chamonix_chalet",
    sourceType: "forum",
    sourceName: "Forum ski public",
    title: "Arriver de nuit à Chamonix quand il neige",
    url: "https://example.com/forum/chamonix-arrivee-neige",
    snippet: "Les voyageurs demandent souvent pneus neige, parking, chauffage, accès et location de matériel.",
    extractedText: "Accès neige, météo, chauffage, cheminée, parking, restaurants saisonniers et équipements ski.",
    publishedAt: "2026-02-18T17:00:00.000Z",
    relevanceScore: 93,
    credibilityScore: 76,
    legalStatus: "allowed_public",
    createdAt: "2026-05-04T15:06:00.000Z",
  },
  {
    id: "src_paris_reddit_studio",
    scannerRunId: "scan_paris_studio",
    sourceType: "reddit",
    sourceName: "Reddit API mock",
    title: "Paris Airbnb guests confused by metro, door codes and old buildings",
    url: "https://reddit.example/r/travel/comments/paris-airbnb-mock",
    snippet: "Travelers mention door codes, elevator absence, noise, metro instructions and unclear building rules.",
    extractedText: "Metro, codes, ascenseur absent, bruit, règlement copropriété, sécurité, restaurants, check-in autonome.",
    publishedAt: "2026-04-29T20:20:00.000Z",
    relevanceScore: 89,
    credibilityScore: 69,
    legalStatus: "official_api_preferred",
    createdAt: "2026-05-05T16:03:00.000Z",
  },
];

export const mockScannerInsights: ScannerInsight[] = [
  {
    id: "ins_biarritz_parking",
    scannerRunId: "scan_biarritz_airbnb_pains",
    prospectId: "pros_biarritz_ocean",
    type: "location_pain",
    label: "Parking difficile en haute saison",
    description: "Les voyageurs cherchent des instructions claires sur stationnement, dépôt bagages et arrivée tardive autour des plages.",
    severity: "high",
    frequency: 87,
    city: "Biarritz",
    country: "France",
    propertyType: "logement proche mer",
    guestProfile: "familles, couples premium, voyageurs internationaux",
    ownerPainPoint: "Messages répétitifs avant arrivée et risque de mauvais avis sur l'accès.",
    guestPainPoint: "Ne pas savoir où se garer ni comment accéder facilement au logement.",
    businessOpportunity: "Transformer les consignes parking et plage en assistant QR code multilingue.",
    recommendedConciergeFeature: "FAQ parking + carte locale + instructions arrivée",
    outreachAngle: "Absorber les questions parking/plage en haute saison sans augmenter le support.",
    evidence: "Forum public et presse locale mentionnent parking saturé et mobilité estivale.",
    sourceIds: ["src_biarritz_forum_parking", "src_biarritz_local_press_season"],
    confidenceScore: 86,
    createdAt: "2026-05-05T09:15:00.000Z",
  },
  {
    id: "ins_biarritz_surf_upsell",
    scannerRunId: "scan_biarritz_airbnb_pains",
    prospectId: "pros_biarritz_ocean",
    type: "upsell_opportunity",
    label: "Surf, plage et restaurants comme upsell naturel",
    description: "Le contexte local crée des opportunités de recommandations et partenariats à intégrer dans le futur majordome IA.",
    severity: "medium",
    frequency: 74,
    city: "Biarritz",
    country: "France",
    propertyType: "logement proche mer",
    guestProfile: "touristes loisirs, familles, voyageurs internationaux",
    ownerPainPoint: "Les recommandations locales ne sont pas structurées ni monétisées.",
    guestPainPoint: "Choisir les bonnes plages, cours de surf et restaurants sans friction.",
    businessOpportunity: "Créer une expérience premium avec recommandations locales et upsells partenaires.",
    recommendedConciergeFeature: "Recommandations locales + upsell activités",
    outreachAngle: "Faire du guide d'accueil un canal de revenus additionnels et d'expérience premium.",
    evidence: "Sources locales et discussion hôte sur questions plage/restaurants.",
    sourceIds: ["src_biarritz_reddit_questions", "src_biarritz_local_press_season"],
    confidenceScore: 79,
    createdAt: "2026-05-05T09:15:30.000Z",
  },
  {
    id: "ins_chamonix_snow_access",
    scannerRunId: "scan_chamonix_chalet",
    prospectId: "pros_chamonix_multilingual",
    type: "property_context",
    label: "Accès neige et météo pour chalets montagne",
    description: "Les voyageurs ont besoin d'instructions dynamiques sur neige, chauffage, parking, équipement ski et arrivée de nuit.",
    severity: "high",
    frequency: 91,
    city: "Chamonix",
    country: "France",
    propertyType: "chalet montagne",
    guestProfile: "skieurs internationaux, familles, groupes",
    ownerPainPoint: "Support multilingue saisonnier et questions répétitives météo/accès.",
    guestPainPoint: "Arriver sereinement avec météo, neige, parking et chauffage maîtrisés.",
    businessOpportunity: "Assistant montagne multilingue par QR code avec FAQ ski et partenaires locaux.",
    recommendedConciergeFeature: "Module météo/accès + FAQ ski multilingue",
    outreachAngle: "Réduire les messages saisonniers et rassurer les voyageurs internationaux avant arrivée.",
    evidence: "Forum ski public et signaux de destination montagne.",
    sourceIds: ["src_chamonix_forum_snow"],
    confidenceScore: 90,
    createdAt: "2026-05-04T15:09:00.000Z",
  },
  {
    id: "ins_paris_old_building",
    scannerRunId: "scan_paris_studio",
    prospectId: "pros_paris_camille",
    type: "guest_problem",
    label: "Immeubles anciens, codes et bruit à Paris",
    description: "Les studios urbains doivent clarifier ascenseur, codes, métro, bruit et règlement copropriété.",
    severity: "medium",
    frequency: 76,
    city: "Paris",
    country: "France",
    propertyType: "studio urbain",
    guestProfile: "couples, voyageurs étrangers, courts séjours",
    ownerPainPoint: "Mêmes questions sur accès, métro, ascenseur et règles d'immeuble.",
    guestPainPoint: "Comprendre rapidement codes, transports et contraintes d'un immeuble ancien.",
    businessOpportunity: "FAQ d'arrivée ultra courte + consignes copropriété + recommandations métro/restaurants.",
    recommendedConciergeFeature: "Check-in autonome + guide transport + règles copropriété",
    outreachAngle: "Éviter les messages répétitifs sur accès et métro pour des voyageurs étrangers.",
    evidence: "Discussion Reddit mock et signaux publics sur appartements parisiens.",
    sourceIds: ["src_paris_reddit_studio"],
    confidenceScore: 78,
    createdAt: "2026-05-05T16:04:00.000Z",
  },
];

export const mockPropertyContexts: PropertyContext[] = [
  {
    id: "propctx_nice_villa",
    prospectId: "pros_nice_villa",
    propertyType: "villa premium proche mer",
    locationType: "mer premium",
    estimatedCapacity: 8,
    premiumLevel: "high",
    accessComplexity: 78,
    weatherSensitivity: 72,
    seasonality: "forte saison estivale",
    guestProfile: "familles, groupes premium, voyageurs internationaux",
    operationalRisks: ["climatisation", "parking", "piscine", "demandes VIP", "arrivées tardives"],
    likelyQuestions: ["Comment accéder à la villa ?", "Où stationner ?", "Comment utiliser la piscine ?", "Quels restaurants réserver ?"],
    recommendedConciergeFeatures: ["QR code", "FAQ équipements", "upsell transferts", "recommandations premium"],
    confidenceScore: 87,
    createdAt: "2026-05-05T09:00:00.000Z",
    updatedAt: "2026-05-05T09:00:00.000Z",
  },
  {
    id: "propctx_chamonix_chalet",
    prospectId: "pros_chamonix_multilingual",
    propertyType: "chalet montagne",
    locationType: "montagne internationale",
    estimatedCapacity: 6,
    premiumLevel: "medium",
    accessComplexity: 86,
    weatherSensitivity: 94,
    seasonality: "hiver et vacances ski",
    guestProfile: "skieurs internationaux et familles",
    operationalRisks: ["neige", "chauffage", "accès nuit", "parking", "équipement ski"],
    likelyQuestions: ["Faut-il des pneus neige ?", "Comment régler le chauffage ?", "Où louer les skis ?"],
    recommendedConciergeFeatures: ["assistant multilingue", "météo locale", "FAQ ski", "partenaires station"],
    confidenceScore: 90,
    createdAt: "2026-05-04T15:12:00.000Z",
    updatedAt: "2026-05-04T15:12:00.000Z",
  },
];

export const mockLocationContexts: LocationContext[] = [
  {
    id: "locctx_biarritz",
    city: "Biarritz",
    country: "France",
    neighborhood: null,
    climateType: "océanique côtier",
    tourismType: "plage, surf, premium, international",
    seasonality: "pic juillet-août",
    transportContext: "voiture fréquente, stationnement contraint, gare/aéroport proches",
    parkingDifficulty: "high",
    weatherRisks: ["météo changeante", "pluie courte", "vent océan"],
    localActivities: ["surf", "plage", "restaurants", "golf", "excursions Pays basque"],
    commonGuestQuestions: ["Où se garer ?", "Quelle plage choisir ?", "Où prendre un cours de surf ?", "Quels restaurants réserver ?"],
    upsellOpportunities: ["cours de surf", "restaurants", "transfert", "late checkout", "location vélo"],
    operationalConstraints: ["parking", "arrivées tardives", "saison haute", "voyageurs internationaux"],
    createdAt: "2026-05-05T09:00:00.000Z",
    updatedAt: "2026-05-05T09:00:00.000Z",
  },
  {
    id: "locctx_paris",
    city: "Paris",
    country: "France",
    neighborhood: null,
    climateType: "urbain tempéré",
    tourismType: "culture, business, international",
    seasonality: "forte toute l'année",
    transportContext: "métro central, marche, taxis, gares et aéroports",
    parkingDifficulty: "high",
    weatherRisks: ["pluie", "canicule ponctuelle"],
    localActivities: ["musées", "restaurants", "shopping", "événements"],
    commonGuestQuestions: ["Quel métro prendre ?", "Y a-t-il un ascenseur ?", "Comment utiliser les codes ?", "Le quartier est-il bruyant ?"],
    upsellOpportunities: ["guide restaurants", "transfert aéroport", "billets musées", "bagagerie"],
    operationalConstraints: ["codes d'immeuble", "bruit", "règlement copropriété", "voyageurs étrangers"],
    createdAt: "2026-05-05T09:00:00.000Z",
    updatedAt: "2026-05-05T09:00:00.000Z",
  },
  {
    id: "locctx_chamonix",
    city: "Chamonix",
    country: "France",
    neighborhood: null,
    climateType: "montagne froide",
    tourismType: "ski, randonnée, premium, international",
    seasonality: "hiver et été montagne",
    transportContext: "voiture, navettes, gare, accès météo-dépendant",
    parkingDifficulty: "medium",
    weatherRisks: ["neige", "verglas", "froid", "fermetures saisonnières"],
    localActivities: ["ski", "randonnée", "restaurants saisonniers", "location matériel"],
    commonGuestQuestions: ["Faut-il des chaînes ?", "Où louer les skis ?", "Comment accéder s'il neige ?"],
    upsellOpportunities: ["location ski", "cours de ski", "transfert gare", "restaurants"],
    operationalConstraints: ["météo", "chauffage", "arrivée nuit", "langues"],
    createdAt: "2026-05-04T15:00:00.000Z",
    updatedAt: "2026-05-04T15:00:00.000Z",
  },
];

export const mockScannerReports: ScannerReport[] = [
  {
    scannerRunId: "scan_biarritz_airbnb_pains",
    executiveSummary: "Biarritz concentre des douleurs fortes autour du parking, des arrivées tardives, des recommandations locales et du pic saisonnier. Le majordome IA peut être vendu comme couche d'automatisation haute saison et guide premium local.",
    dominantPainPoints: ["parking", "check-in tardif", "questions plage/surf", "voyageurs internationaux", "restaurants"],
    topCommercialAngles: ["Absorber les messages de haute saison", "Transformer le guide local en expérience premium", "Réduire les mauvais avis liés à l'arrivée"],
    recommendedConciergeSetup: {
      languages: ["fr", "en", "es"],
      frequentQuestions: ["Où se garer ?", "Quelle plage choisir ?", "Comment arriver tard ?", "Où réserver un restaurant ?"],
      documentsToRequest: ["Instructions d'accès", "Guide parking", "Partenaires surf", "Recommandations restaurants"],
      features: ["QR code", "FAQ multilingue", "recommandations locales", "upsell activités"],
      automationLevel: "advanced",
      qrCodeRecommended: true,
    },
    v3Placeholders: ["Photo Analysis", "Street View Context", "Neighborhood Visual Signals"],
  },
];

export function getScannerRunById(id: string) {
  return mockScannerRuns.find((run) => run.id === id) ?? null;
}

export function getScannerSourcesByRunId(scannerRunId: string) {
  return mockScannedSources.filter((source) => source.scannerRunId === scannerRunId);
}

export function getScannerInsightsByRunId(scannerRunId: string) {
  return mockScannerInsights.filter((insight) => insight.scannerRunId === scannerRunId);
}

export function getScannerInsightsByProspectId(prospectId: string) {
  return mockScannerInsights.filter((insight) => insight.prospectId === prospectId);
}

export function getPropertyContextByProspectId(prospectId: string) {
  return mockPropertyContexts.find((context) => context.prospectId === prospectId) ?? null;
}

export function getLocationContextByCity(city: string) {
  return mockLocationContexts.find((context) => context.city.toLowerCase() === city.toLowerCase()) ?? null;
}

export function getScannerReportByRunId(scannerRunId: string) {
  return mockScannerReports.find((report) => report.scannerRunId === scannerRunId) ?? null;
}
